name: pypi
description: Publish to PyPi
inputs:
  python-version:
    description: 'Python version'
    required: false
    default: '3.6'
  tag:
    description: 'Commit / Branch / Tag / SHA to checkout'
    required: false
    default: ''
  publish:
    description: 'Publish'
    required: false
    default: 'test+pypi'
    # {pypi, test, test+pypi}
  pypi-password:
    required: true
  test-password: 
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: ${{ inputs.tag }}
    - name: Setup Python ${{ inputs.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}
    - name: Install dependencies for building package
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
      shell: bash
    - name: Build a binary wheel and a source tarball
      run: |
        python setup.py sdist bdist_wheel
      shell: bash
    - name: Publish distribution 📦 to Test PyPI
      if: ${{ contains(inputs.publish, 'test') }}
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ inputs.test-password }}
        repository_url: https://test.pypi.org/legacy/
    - name: Publish distribution 📦 to PyPI
      if: ${{ contains(inputs.publish, 'pypi') }}
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ inputs.pypi-password }}
        repository_url: https://upload.pypi.org/legacy/