name: Publish to PyPi
description: Publish to PyPi
inputs:
  python-version:
    description: 'Python version'
    required: false
    default: '3.6'
  tag:
    description: 'Commit / Branch / Tag / SHA to checkout'
    required: false
    default: ''
  publish:
    description: 'Publish'
    required: false
    default: 'test+pypi'
    # {pypi, test, test+pypi, auto}
    # auto is an alias for test+pypi
  password-pypi:
    description: 'PyPi password'
    required: true
  password-test:
    description: 'Test PyPi password'
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        ref: ${{ inputs.tag }}
    - name: Setup Python ${{ inputs.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ inputs.python-version }}
    - name: Install dependencies for building package
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
      shell: bash
    - name: Build a binary wheel and a source tarball
      run: |
        python setup.py sdist bdist_wheel
      shell: bash
    - name: Publish distribution 📦 to Test PyPI
      if: |
        inputs.publish == 'test' || 
        inputs.publish == 'test+pypi' || 
        inputs.publish == 'auto'
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ inputs.password-test }}
        repository_url: https://test.pypi.org/legacy/
    - name: Publish distribution 📦 to PyPI
      if: |
        inputs.publish == 'pypi' || 
        inputs.publish == 'test+pypi' || 
        inputs.publish == 'auto'
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ inputs.password-pypi }}
        repository_url: https://upload.pypi.org/legacy/