name: Run tests
description: Run tests

on:

  workflow_dispatch:
    inputs:
      tag:
        description: 'Commit / Branch / Tag / SHA to checkout'
        required: false
        default: ''
      python-version:
        description: 'Python version'
        required: true
        default: '3.6'
      pytorch-version:
        description: 'PyTorch version'
        required: true
        default: '1.8'

  workflow_call:
    inputs:
      tag:
        description: 'Commit / Branch / Tag / SHA to checkout'
        required: false
        default: ''
        type: string
      python-version:
        description: 'Python version'
        required: true
        default: '3.6'
        type: string
      pytorch-version:
        description: 'PyTorch version'
        required: true
        default: '1.8'
        type: string

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.tag }}
      - uses: conda-incubator/setup-miniconda@v3
        with:
          mamba-version: "*"
          python-version: ${{ inputs.python-version }}
          channels: conda-forge,pytorch
          conda-remove-defaults: "true"
          activate-environment: test-env
      - name: Install dependencies (using mamba)
        shell: bash -el {0}
        env:
          PYTORCH_VERSION: ${{ inputs.pytorch-version }}
        run: |
          [[ "$PYTORCH_VERSION" != "1.4" ]] && mamba install pytorch=${PYTORCH_VERSION}
          mamba install pytest
      - name: Install dependencies (using pip)
        if: ${{ inputs.pytorch-version == '1.4' }}
        shell: bash -el {0}
        env:
          PYTORCH_VERSION: ${{ inputs.pytorch-version }}
        run: |
          pip install "numpy<1.24" "torch==${PYTORCH_VERSION}"
      - name: Test with pytest
        shell: bash -el {0}
        env:
          # This is to avoid a
          PYTHONIOENCODING: utf-8
          LANG: en_US.UTF-8
          LC_ALL: en_US.UTF-8
        run: |
          pip install .
          pytest
